# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutt',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
