# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_auto_20160519_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutt',
            name='date_n_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 19, 18, 10, 2, 115637, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
